#!/usr/bin/env python3
"""gen_qc_params.py — 把QC基矩阵编译成Verilog参数头文件 qc_params.vh

每个连接条目16bit: {valid[15], 2'b00, idx[13:8], 2'b00, shift[5:0]}
  ROWCONN: 40个块行 x 最多6条 (idx=块列号bj, shift=s)  -> syndrome计算
  COLCONN: 50个块列 x 最多4条 (idx=块行号bi, shift=s)  -> 冲突计数
  COLDEG : 50个块列的列重(4bit)                        -> 阈值 T=deg-1
"""
import sys

MB, NB, Z = 40, 50, 40
MAX_RD, MAX_CD = 6, 4

B = [[int(v) for v in line.split()] for line in open(sys.argv[1]) if line.strip()]
assert len(B) == MB and all(len(r) == NB for r in B)

rows = [[] for _ in range(MB)]   # (bj, s)
cols = [[] for _ in range(NB)]   # (bi, s)
for bi in range(MB):
    for bj in range(NB):
        s = B[bi][bj]
        if s >= 0:
            rows[bi].append((bj, s)); cols[bj].append((bi, s))
assert max(len(r) for r in rows) <= MAX_RD and max(len(c) for c in cols) <= MAX_CD

def entry(idx, s, v): return (v << 15) | (idx << 8) | s

def flat(table, width, maxe):
    """拼成Verilog字面量, 条目e的位域在 ((i*maxe+e)*16) +: 16, 即低位在前 -> 串里倒序"""
    ws = []
    for lst in table:
        padded = lst + [(0, 0)] * (maxe - len(lst))
        for idx, s in padded[:maxe]:
            ws.append(entry(idx, s, 1 if (idx, s) in lst and len([x for x in lst if x == (idx, s)]) else 0))
    # 上面valid判断对pad(0,0)会误判: 显式重建
    ws = []
    for lst in table:
        for e in range(maxe):
            if e < len(lst):
                idx, s = lst[e]; ws.append(entry(idx, s, 1))
            else:
                ws.append(0)
    return ws

rw = flat(rows, 16, MAX_RD)
cw = flat(cols, 16, MAX_CD)

with open('qc_params.vh', 'w') as f:
    f.write("// AUTO-GENERATED by gen_qc_params.py — do not edit\n")
    f.write(f"localparam integer MBLK={MB}, NBLK={NB}, ZP={Z};\n")
    f.write(f"localparam integer MAX_RD={MAX_RD}, MAX_CD={MAX_CD};\n")
    def emit(name, ws):
        n = len(ws)
        f.write(f"localparam [{n*16-1}:0] {name} = {{\n")
        # 串接字面量: 最左=最高位 -> 倒序输出, 条目i*16+:16对应ws[i]
        items = [f"16'h{w:04x}" for w in reversed(ws)]
        for i in range(0, n, 8):
            f.write("  " + ", ".join(items[i:i+8]) + ("," if i+8 < n else "") + "\n")
        f.write("};\n")
    emit("ROWCONN", rw)
    emit("COLCONN", cw)
    f.write(f"localparam [{NB*4-1}:0] COLDEG = {{\n  ")
    f.write(", ".join(f"4'd{len(cols[j])}" for j in reversed(range(NB))))
    f.write("\n};\n")
print(f"qc_params.vh written: {sum(len(r) for r in rows)} nonzero blocks, "
      f"col degrees {sorted(set(len(c) for c in cols))}")
