#!/usr/bin/env python3
"""Generate QC-LDPC Verilog parameters from the base matrix."""

from __future__ import annotations

import sys
from pathlib import Path


MBLK = 40
NBLK = 50
ZP = 40
MAX_ITER = 50
MAX_RD = 6
MAX_CD = 4


def read_base(path: Path) -> list[list[int]]:
    rows: list[list[int]] = []
    with path.open() as f:
        for line in f:
            if line.strip():
                rows.append([int(x) for x in line.split()])

    if len(rows) != MBLK or any(len(row) != NBLK for row in rows):
        raise SystemExit(f"base matrix must be {MBLK}x{NBLK}")
    return rows


def pack_entry(valid: bool, idx: int, shift: int) -> int:
    if not valid:
        return 0
    if idx < 0 or idx > 0x3F:
        raise ValueError(f"idx out of 6-bit range: {idx}")
    if shift < 0 or shift > 0x3F:
        raise ValueError(f"shift out of 6-bit range: {shift}")
    return (1 << 15) | (idx << 8) | shift


def emit_vec(name: str, width: int, values: list[int], f) -> None:
    total_width = width * len(values)
    hex_width = (total_width + 3) // 4
    value = 0
    for i, v in enumerate(values):
        value |= v << (i * width)
    print(f"localparam [{total_width-1}:0] {name} = {total_width}'h{value:0{hex_width}x};", file=f)


def main() -> int:
    if len(sys.argv) != 2:
        print(f"usage: {sys.argv[0]} <base_matrix.txt>", file=sys.stderr)
        return 1

    root = Path(__file__).resolve().parents[1]
    base = read_base(Path(sys.argv[1]))

    row_entries: list[int] = []
    row_degs: list[int] = []
    for bi, row in enumerate(base):
        conns = [(bj, s) for bj, s in enumerate(row) if s >= 0]
        if len(conns) > MAX_RD:
            raise SystemExit(f"row block {bi} degree {len(conns)} > MAX_RD")
        row_degs.append(len(conns))
        for e in range(MAX_RD):
            if e < len(conns):
                bj, s = conns[e]
                row_entries.append(pack_entry(True, bj, s))
            else:
                row_entries.append(pack_entry(False, 0, 0))

    col_entries: list[int] = []
    col_degs: list[int] = []
    for bj in range(NBLK):
        conns = [(bi, base[bi][bj]) for bi in range(MBLK) if base[bi][bj] >= 0]
        if len(conns) > MAX_CD:
            raise SystemExit(f"column block {bj} degree {len(conns)} > MAX_CD")
        col_degs.append(len(conns))
        for e in range(MAX_CD):
            if e < len(conns):
                bi, s = conns[e]
                col_entries.append(pack_entry(True, bi, s))
            else:
                col_entries.append(pack_entry(False, 0, 0))

    nonzero_blocks = sum(row_degs)
    if nonzero_blocks != 197:
        raise SystemExit(f"unexpected nonzero blocks: {nonzero_blocks}")
    if min(col_degs) != 3 or max(col_degs) != 4:
        raise SystemExit(f"unexpected column degree range: {min(col_degs)}..{max(col_degs)}")
    if min(row_degs) < 4 or max(row_degs) > 6:
        raise SystemExit(f"unexpected row degree range: {min(row_degs)}..{max(row_degs)}")

    out = root / "rtl" / "qc_params.vh"
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w") as f:
        print("// Auto-generated by tools/gen_qc_params.py. Do not edit by hand.", file=f)
        print("// Entry format: {valid[15], idx[13:8], shift[5:0]}; bit[14] unused.", file=f)
        print(f"localparam integer MBLK = {MBLK};", file=f)
        print(f"localparam integer NBLK = {NBLK};", file=f)
        print(f"localparam integer ZP = {ZP};", file=f)
        print(f"localparam integer MAX_RD = {MAX_RD};", file=f)
        print(f"localparam integer MAX_CD = {MAX_CD};", file=f)
        print(f"localparam integer QC_MAX_ITER = {MAX_ITER};", file=f)
        emit_vec("ROWCONN", 16, row_entries, f)
        emit_vec("COLCONN", 16, col_entries, f)
        emit_vec("COLDEG", 4, col_degs, f)

    print(f"generated {out}")
    print(f"nonzero_blocks={nonzero_blocks}, col_degree={min(col_degs)}..{max(col_degs)}, row_degree={min(row_degs)}..{max(row_degs)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
